export const menbbc = [
    { names: "BIGWI Abdoul Djabal", role: "pg" },
    { names: "Chad Bowie Jordan", role: "sg" },
    { names: "MUGABE Aristide", role: "sf" },
    { names: "Done Carlos Alejandro", role: "sf" },
    { names: "IRADUKUNDA CYUZUZO Cedrick", role: "pf" },
    { names: "IRAKOZE HERVE Hodal", role: "cr" },
    { names: "IRUMVA Heritier", role: "pg" },
    { names: "KAZENEZA Emile Galois", role: "sg" },
    { names: "MUGABO Jonathan", role: "pf" },
    { names: "MURWANASHYAKA PATRICK", role: "cr" },
    { names: "NDOLI Jean Paul", role: "pg" },
    { names: "NGOGA Elias", role: "sg" },
    { names: "NIJIMBERE Guibert", role: "sf" },
    { names: "NIYIBIZI Theogene", role: "pf" },
    { names: "NIYUBAHWE YAMIN", role: "cr" },
    { names: "RUTAYISIRE IMANI", role: "pg" },
    { names: "Ruterana Christian", role: "sg" },
    { names: "RWEMA PATRICK", role: "sf" },
    { names: "SONGA Victor", role: "pf" },
    { names: "Twizeyimana Cyiza Chandelier", role: "cr" }
];
export const wbbc = [
    { names: "Nelly Sandra NSANZABAGANWA", role: "pg" },
    { names: "UWIMPUHWE Henriette", role: "sg" },
    { names: "Ntawutarama Deborah", role: "sf" },
    { names: "Gasherebuka Victoire", role: "pf" },
    { names: "Akariza Nelly", role: "cr" },
    { names: "BYUKUSENGE IRUMVA Christiane", role: "pg" },
    { names: "UWASE Eugenie Kellen", role: "sg" },
    { names: "Merveille Obrou Julia", role: "sf" },
    { names: "Irakoze Epiphanie", role: "pf" },
    { names: "Mumporeze Keza Benitha", role: "cr" },
    { names: "Uwera Kevine", role: "pg" },
    { names: "Umwiza Edyne", role: "sg" },
    { names: "Muteteramana Divine", role: "sf" },
    { names: "Awor Leticia", role: "pf" },
    { names: "Veronica Keita Gbenakpon", role: "cr" },
    { names: "Brionna Budgetts", role: "pg" }
];